# Generated by Django 4.2.3 on 2023-08-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_post_project_link_post_project_link_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
