# Generated by Django 4.1.4 on 2023-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='linktree_link',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
